version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "1234:1000"
    volumes:
      - ./:/usr/src/app
  
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
